import re
# <div class="buy-table__price">(.+)руб\. </div>
text = ' <!--noindex--> <div> <div id="protec-table" class="buy-header pharmacy-company-uteka"> <span class="buy-header__pharmacy-name">Заказать в Ютеке</span> <img src="/upload/photo/logo-new.png?v21" alt="Ютеке" style="width:85px;height:25px;"/> </div> <div class="buy-table pharmacy"> <div class="buy-table__item"> <div class="buy-table__title"> Евра, 203 мкг+33.9 мкг/24 ч, пластырь трансдермальный, 3 шт. </div> <div class="buy-table__price"> от 1,120 руб. </div> <div class="buy-table__order"> <a rel="nofollow" href="https://uteka.ru/product/evra-288929/?utm_source=vidal&amp;utm_medium=cpc&amp;utm_campaign=https://www.vidal.ru/drugs/evra__6659" target="_blank" class="to-ga" data-code="uteka" data-id="212710"> <button class="base-button">Заказать</button> </a> </div> <div class="buy-table__vendor"> Johnson &amp; Johnson </div> </div> </div> <div style="color: gray; padding: 10px;"> Москва </div> </div> <div> <div id="protec-table" class="buy-header pharmacy-company-planet-health"> <span class="buy-header__pharmacy-name">Заказать в аптеке Планета Здоровья</span> <img src="/upload/photo/planeta.png?v21" alt="аптеке Планета Здоровья" style="width:106px;height:25px;"/> </div> <div class="buy-table pharmacy"> <div class="buy-table__item"> <div class="buy-table__title"> Евра пластырь трансдермальный 203 мкг+33.9 мкг.24 ч 3 шт </div> <div class="buy-table__price"> от 1,252 руб. </div> <div class="buy-table__order"> <a rel="nofollow" href="https://planetazdorovo.ru/ges/25356203/?utm_source=vidal.ru&amp;utm_medium=cpc&amp;utm_campaign=https://www.vidal.ru/drugs/evra__6659" target="_blank" class="to-ga" data-code="planet-health" data-id="215822"> <button class="base-button">Заказать</button> </a> </div> <div class="buy-table__vendor"> ЛТС Ломанн Терапи-Зистеме АГ, Германия </div> </div> </div> <div style="color: gray; padding: 10px;"> Москва </div> </div> <i style="display: none" id="regionFound" data-value="Нет"></i> <i style="display: none" id="regionTitle" data-value="Москва"></i> <i style="display: none" id="cityTitle" data-value="Москва"></i> <i style="display: none" id="districtTitle" data-value="Центральный федеральный округ"></i> <i style="display: none" id="regionIp" data-value="176.25.80.24"></i> <!--noindex--> '

pattern_price = re.compile(r'<div class="buy-table__price">.*?</div>')
pattern_order = re.compile(r'<div class="buy-table__order">.*?</div>')
pattern_img = re.compile(r'<img src="/upload.*?/>')
# <img src="/upload'
match = pattern_price.findall(text)
print(match)
match = pattern_order.findall(text)
print(match)
match = pattern_img.findall(text)
print(match)