version: '3.3'

services:
  bot:
    container_name: tg_bot
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./bot/logs/:/app/bot/logs
    environment:
      WEBAPP_PORT: 8000
    env_file:
      - ./vault.env
    network_mode: host