ID_START = 'START'
ID_ADD = 'ADD'
ID_DEL = 'DEL'
ID_ADDED = 'ADDED'
ID_DELETED = 'DELETED'
ID_VIEW_ACTUAL = 'VIEW_ACTUAL'
ID_VIEW_EXPIRED = 'VIEW_EXPIRED'
ID_CLEAR_EXPIRED = 'CLEAR_EXPIRED'
ID_CANCEL = 'CANCEL'
ID_CANCELLED = 'CANCELLED'
ID_CLEAN = 'CLEAN'
ID_DONE = 'DONE'
ID_NOT_FOUND = 'NOT_FOUND'

ID_TITLE_ACTUAL_DRUGS = 'TITLE_ACTUAL_DRUGS'
ID_TITLE_EXPIRED_DRUGS = 'TITLE_EXPIRED_DRUGS'
ID_TITLE_INPUT_DRUGS_4_DELETE = 'TITLE_INPUT_DRUGS_4_DELETE'

ID_TXT_DRUG_NAME_INPUT = 'TXT_DRUG_NAME_INPUT'

ID_TXT_DRUG_DATE_INPUT = 'TXT_DRUG_DATE_INPUT'

ID_TXT_ERROR_DATE = 'TXT_ERROR_DATE'
ID_TXT_TIME_IS_OVER = 'TXT_TIME_IS_OVER'

ID_TXT_FIRST_AID_KIT_IS_EMPTY = 'TXT_FIRST_AID_KIT_IS_EMPTY'
ID_TXT_EXPIRED_DRUGS_NOT_FOUND = 'TXT_EXPIRED_DRUGS_NOT_FOUND'
